// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: sum.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Sum_SumItems_FullMethodName = "/api.Sum/SumItems"
)

// SumClient is the client API for Sum service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SumClient interface {
	SumItems(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SumItemRequest, SumResponse], error)
}

type sumClient struct {
	cc grpc.ClientConnInterface
}

func NewSumClient(cc grpc.ClientConnInterface) SumClient {
	return &sumClient{cc}
}

func (c *sumClient) SumItems(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[SumItemRequest, SumResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Sum_ServiceDesc.Streams[0], Sum_SumItems_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SumItemRequest, SumResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sum_SumItemsClient = grpc.ClientStreamingClient[SumItemRequest, SumResponse]

// SumServer is the server API for Sum service.
// All implementations must embed UnimplementedSumServer
// for forward compatibility.
type SumServer interface {
	SumItems(grpc.ClientStreamingServer[SumItemRequest, SumResponse]) error
	mustEmbedUnimplementedSumServer()
}

// UnimplementedSumServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSumServer struct{}

func (UnimplementedSumServer) SumItems(grpc.ClientStreamingServer[SumItemRequest, SumResponse]) error {
	return status.Errorf(codes.Unimplemented, "method SumItems not implemented")
}
func (UnimplementedSumServer) mustEmbedUnimplementedSumServer() {}
func (UnimplementedSumServer) testEmbeddedByValue()             {}

// UnsafeSumServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SumServer will
// result in compilation errors.
type UnsafeSumServer interface {
	mustEmbedUnimplementedSumServer()
}

func RegisterSumServer(s grpc.ServiceRegistrar, srv SumServer) {
	// If the following call pancis, it indicates UnimplementedSumServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Sum_ServiceDesc, srv)
}

func _Sum_SumItems_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SumServer).SumItems(&grpc.GenericServerStream[SumItemRequest, SumResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Sum_SumItemsServer = grpc.ClientStreamingServer[SumItemRequest, SumResponse]

// Sum_ServiceDesc is the grpc.ServiceDesc for Sum service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sum_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Sum",
	HandlerType: (*SumServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SumItems",
			Handler:       _Sum_SumItems_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sum.proto",
}
